#!/bin/bash
image_dir=${1%/*}
media_dir=${image_dir}/emby-xy

loop_device=$(cat ${image_dir}/.loop >/dev/null 2>&1 | grep -v config | awk '{print $2}')
if [ -z "${loop_device}" ]; then
    loop_device=$(losetup -f)
fi
losetup -o 10000000 ${loop_device} $1
mount ${loop_device} ${media_dir}
